export const SET_GRID = "SET_GRID";
export const SET_STARTING_ROW = "SET_STARTING_ROW";
export const SET_STARTING_COL = "SET_STARTING_COL";
export const SET_FINISH_ROW = "SET_FINISH_ROW";
export const SET_FINISH_COL = "SET_FINISH_COL";

export const SET_MOUSE_IS_PRESSED = "SET_MOUSE_IS_PRESSED";

export const IS_DRAGGING = "IS_DRAGGING";

export const SET_ORIGINAL_ROW = "SET_ORIGINAL_ROW";
export const SET_ORIGINAL_COL = "SET_ORIGINAL_COL";

export const SET_TRANSLATE_ROW = "SET_TRANSLATE_ROW";
export const SET_TRANSLATE_COL = "SET_TRANSLATE_COL";

export const SET_LAST_TRANSLATE_ROW = "SET_LAST_TRANSLATE_ROW";
export const SET_LAST_TRANSLATE_COL = "SET_LAST_TRANSLATE_COL";
export const SET_DISTANCE_METHOD = "SET_DISTANCE_METHOD";
export const SET_ALLOW_DIAGONAL = "SET_ALLOW_DIAGONAL";

export const SET_ALGORITHM = "SET_ALGORITHM";

export const SET_HALT = "SET_HALT";
export const SET_TIMEOUTIDS = "SET_TIMEOUTIDS";
